### ISSUE TITLE
Reducing Duplicate CSS

### ISSUE THREAD

**Issue by jim-rosales** [webgodess/prj-rev-bwfs-dasmoto#6]
When writing CSS, it is best not to have duplicate code as it makes it harder to maintain a project. Here you apply the following CSS to three different sections
```CSS
font-family: Helvetica;
font-size: 32px;
font-weight: bold;
color: white;
```

Instead of applying the styles to each section separately it is better to do the following:
```CSS
/* Apply the style all the elements share */
div h2 {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
/* Apply the unique background color they all have */
#brush {
  background-color: mediumspringgreen;
}
#frame {
  background-color: lightcoral;
}
#paint {
  background-color: skyblue;
}
```

https://github.com/webgodess/prj-rev-bwfs-dasmoto/blob/494adafbe1325ad8f2aa0ec13966676a2e65fdf8/Dasmoto'%20Arts%20%26Crafts/dasmoto.css#L31-L37
